"""create scheduler runs table

Revision ID: 0c8db116f4f2
Revises: deb3a13a3c36
Create Date: 2026-07-14 00:34:58.711651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c8db116f4f2"
down_revision: Union[str, Sequence[str], None] = "deb3a13a3c36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduler_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scheduler_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("retry_attempts", sa.Integer(), nullable=False),
        sa.Column("impact_score", sa.Float(), nullable=True),
        sa.Column("arrivals", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduler_runs_id"), "scheduler_runs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduler_runs_scheduler_name"),
        "scheduler_runs",
        ["scheduler_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduler_runs_started_at"),
        "scheduler_runs",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduler_runs_status"), "scheduler_runs", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduler_runs_status"), table_name="scheduler_runs")
    op.drop_index(op.f("ix_scheduler_runs_started_at"), table_name="scheduler_runs")
    op.drop_index(op.f("ix_scheduler_runs_scheduler_name"), table_name="scheduler_runs")
    op.drop_index(op.f("ix_scheduler_runs_id"), table_name="scheduler_runs")
    op.drop_table("scheduler_runs")
    # ### end Alembic commands ###
