from enum import StrEnum


class ErrorCode(StrEnum):
    HTTP_TIMEOUT = "HTTP_TIMEOUT"
    HTTP_REQUEST_FAILED = "HTTP_REQUEST_FAILED"
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
